# Generated by Django 3.1.2 on 2020-10-14 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(help_text='Enter category name', max_length=100),
        ),
        migrations.AlterField(
            model_name='comments',
            name='text',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='sections',
            name='name',
            field=models.CharField(help_text='Enter section name', max_length=70),
        ),
        migrations.AlterField(
            model_name='subsections',
            name='name',
            field=models.CharField(help_text='Enter subsection name', max_length=70),
        ),
        migrations.AlterField(
            model_name='topics',
            name='name',
            field=models.CharField(help_text='Enter topic name', max_length=70),
        ),
    ]
